'use strict'
// メニューバー
  $('#hanberger').click(function(){
    $('#sabmenu').toggle('slow');
  });
  $('#close').click(function(){
    $('#sabmenu').toggle('slow');
  });
// へっだー
  $(function(){
    $('.headli').mouseenter(function(){
      $('img',this).css('transform','rotateZ(30deg)');
      console.log('over');
      })
      .mouseleave(function(){
        $('img',this).css('transform','rotateZ(0deg)');
        console.log('out');
    });
  });
  // 役切替
  $('#bt1').click(function(){
    $('.hanli').css('background','#1e01a0');
    $('#bt1').css('background','#4153f5');
    $('.absol').css('display','none');
    $('#han1').css('display','block');
  });
  $('#bt2').click(function(){
    $('.hanli').css('background','#1e01a0');
    $('#bt2').css('background','#4153f5');
    $('.absol').css('display','none');
    $('#han2').css('display','block');
  });
  $('#bt3').click(function(){
    $('.hanli').css('background','#1e01a0');
    $('#bt3').css('background','#4153f5');
    $('.absol').css('display','none');
    $('#han3').css('display','block');
  });
  $('#bt4').click(function(){
    $('.hanli').css('background','#1e01a0');
    $('#bt4').css('background','#4153f5');
    $('.absol').css('display','none');
    $('#han6').css('display','block');
  });
  $('#bt5').click(function(){
    $('.hanli').css('background','#1e01a0');
    $('#bt5').css('background','#4153f5');
    $('.absol').css('display','none');
    $('#mangan').css('display','block');
  });
  $('#bt6').click(function(){
    $('.hanli').css('background','#1e01a0');
    $('#bt6').css('background','#4153f5');
    $('.absol').css('display','none');
    $('#yakuman').css('display','block');
  });
  $('#bt7').click(function(){
    $('.hanli').css('background','#1e01a0');
    $('#bt7').css('background','#4153f5');
    $('.absol').css('display','none');
    $('#yakuman2').css('display','block');
  });
  $(function(){
    $('.hanli').mouseenter(function(){
      $(this).css('background','');
      $(this).toggleClass('over1');
      })
      .mouseleave(function(){
        $(this).toggleClass('over1');
    });
  });
  $('#bt_1').click(function(){
    $('.nakili').css('background','#027407');
    $('#bt_1').css('background','#02a80a');
    $('.absol2').css('display','none');
    $('#menzen').css('display','block');
  });
  $('#bt_2').click(function(){
    $('.nakili').css('background','#027407');
    $('#bt_2').css('background','#02a80a');
    $('.absol2').css('display','none');
    $('#kuisagari').css('display','block');
  });
  $('#bt_3').click(function(){
    $('.nakili').css('background','#027407');
    $('#bt_3').css('background','#02a80a');
    $('.absol2').css('display','none');
    $('#sonota').css('display','block');
  });
  $('#bt_4').click(function(){
    $('.nakili').css('background','#027407');
    $('#bt_4').css('background','#02a80a');
    $('.absol2').css('display','none');
    $('#bornas').css('display','block');
  });
  $(function(){
    $('.nakili').mouseenter(function(){
      $(this).css('background','');
      $(this).toggleClass('over2');
      })
      .mouseleave(function(){
        $(this).toggleClass('over2');
    });
  });
